name: Pipeline

on:
  push:
    branches: [ $default-branch ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Pipeline

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Welcome from Pipeline

        

        


